### ISSUE TITLE
OODMetrics: __new__() missing 1 required positional argument: 'task'

### ISSUE THREAD

**Issue by yezxxx** [kkirchheim/pytorch-ood#2]
using CIFAR 10 benchmark example raise this error

**Comment by kkirchheim** [comment]
Hi, 
I assume that this happens because `torchmetrics` changed the `task` attribute from optional to required in v0.11.0. 
This has already been fixed (by setting the required version to 0.10.2), but the fixed version has not been deployed to PyPI yet. 
I will create a new release of the library and deploy it. Afterwards, please, update and verify.
