### ISSUE TITLE
WOODS is a method worth adding!

### ISSUE THREAD

**Issue by Hengwei-Zhao96** [kkirchheim/pytorch-ood#30]
Hi,

Thanks for pytorch-ood, which is very user-friendly!

I noticed that there is a method called WOODS (Training OOD Detectors in their Natural Habitats), which is different from the existing OOD methods. Maybe this method can be added to pytorch-ood.

**Comment by kkirchheim** [comment]
Hi, thank you for the suggestion. Currently, I am unfortunately short on time. If you have a working implementation of this method, I would appreciate if you could wrap it up in the pytorch-ood API and create a pull request. Otherwise, I could only manage to maybe implement it in a couple of weeks, once I have more time available.
