### ISSUE TITLE
Inverse covariance error

### ISSUE THREAD

**Issue by kyoungup** [kkirchheim/pytorch-ood#8]
Hi,

Thank you for this great work. I am actively using this framework. I propose one improvement. Actually, it caused some error.
I used the Mahalanobis detector with resnet models, it made an error when it calculate inverse covariance. I think the reason is that the models made sparse features. It is usual case with resnet models.
Thus, I recommend to use pseudo inverse function.
At 100 line In Mahalanobis.py,
self.precision = torch.linalg.inv(self.cov)
I checked the original author's work. They used the pseudo inverse.

**Comment by kkirchheim** [comment]
Hi, thank you for the report. 

Very recently someone implemented diagonal perturbations to make the matrix invertible (see https://github.com/kkirchheim/pytorch-ood/pull/7). This change should be included in version `0.1.2`, which was released yesterday. Do you still experience this error after updating to the new version? 

Otherwise, you propose to replace https://github.com/kkirchheim/pytorch-ood/blob/320dda863c7c7739783d99b5bbe6ea4ee1c6eea5/src/pytorch_ood/detector/mahalanobis.py#L111 with `torch.linalg.pinv()`, which should be invertible in any case, right?

**Comment by kyoungup** [comment]
I tested it with 0.1.2. The error has gone. Thank you.
I wonder if the replacement with the eye matrix supress the potential issue. Otherwise, I will report you again.
